### ISSUE TITLE
Project page broken

### ISSUE THREAD

**Issue by Razoxane** [Datamart/Komito#1]
https://datamart.github.io/Komito/ looks borked.

**Comment by krailo** [comment]
Hello @Razoxane,

Thank you very much for your comment.  This issue has been temporary fixed with da8c8cd commit.

Sincerely,
Alex K.

**Comment by Razoxane** [comment]
The new page has a mixed content error, and appears to keep attempting to reload, but never succeeds.
![image](https://cloud.githubusercontent.com/assets/3488998/11298499/8bbe0426-8fd3-11e5-9cf4-7f92a7259860.png)

**Comment by vpodk** [comment]
It seems that you are using a cached version. Please clear cache and refresh page.
