### ISSUE TITLE
Add support for Go-Pricing table plugin (on Wordpress)

### ISSUE THREAD

**Issue by philliptmaddox** [Datamart/Komito#16]
I'm using a paid for plugin for Wordpress called "[Go-Pricing](www.go-pricing.com)" and event tracking inside of it (specifically for Paypal buttons in this case) are not working because of its wrappers I believe.

I've created a post and tested the same Paypal button embed code and the event did trigger, but does not trigger inside of the Go-Pricing table.

**Comment by vpodk** [comment]
@philliptmaddox Thank you for contacting us. We hope our explanation email was helpful.
