### ISSUE TITLE
Bounce rate affected

### ISSUE THREAD

**Issue by dduran07** [Datamart/Komito#22]
Bounce rate affected
Hi! I implement the plugin since Google Tag Manager, but this was changing the bounce rate dramatically. How can I solve this point?
Thanks for helping me!

**Comment by vpodk** [comment]
Hi @dduran07, is this issue still actual?

**Comment by dduran07** [comment]
I had to disable the plugin. There is also another problem, which even if I put zero in the actions that I do not need to use, they continue to be launched.

**Comment by krailo** [comment]
Hi @dduran07,

In order to research what may cause issues for you, could you please share a JavaScript code which you have inserted and your web site URL?
Please also shed a light how exactly bounce rate was affected (either screenshot or description would be very helpful).

Thanks,
Alex Krailo

**Comment by vpodk** [comment]
Hi @dduran07, seems you update configuration after main script including.

Please see step 2 Default Komito Analytics configuration: (Put modified configuration code **before** main script.) on [Integration page](https://datamart.github.io/Komito/integration/).

For prevent similar issues I will add one second timeout to script initialization.

**Comment by dduran07** [comment]
Hi Alex! This is the timeline with the bounce rate. The bounce rate low was
when I had published the plugin. The plugin was published in all de site.
Also, send you the code implemented, is the same that instructions page and
the video tutorial.

[image: Imagen integrada 1]


[image: Imagen integrada 2]


*David Israel Durán Terreros*
*Business Intelligence **and Digital Analytics** Consultant *
*Tel: *3115749360
*Skype: davidduran1981*

   - co.linkedin.com/pub/david-durán/46/266/b08/
   <http://co.linkedin.com/pub/david-dur%C3%A1n/46/266/b08/>



<http://about.me/daviddemexico>

2017-06-26 16:26 GMT-05:00 Alex Krailo <notifications@github.com>:

**Comment by krailo** [comment]
Hi David,

Unfortunately, we don't see images in Github issue tracker. Could you please resend images to support@komito.net ?

Thanks,
Alex Krailo

**Comment by vpodk** [comment]
Hi there, if this issue is still actual, try the new `nonInteraction` parameter added to tracking options. By default `'form'`, `'print'`, `'scroll'`, `'video'` events are treated as non-interaction.
For more information, see https://datamart.github.io/Komito/integration/
