### ISSUE TITLE
Using with gtag.js

### ISSUE THREAD

**Issue by vilbht** [Datamart/Komito#23]
Hi there

There's a new tag called gtag.js being made available. I had a few questions:
 - Is there any overlap between its functionality and what that Komito does? 
 - Does the implementation of Komito get affected?
 - Can gtag and komito together yield a more enhanced setup vs. when working with the regular analytics.js tag? 

https://developers.google.com/analytics/devguides/collection/gtagjs/

Thanks!

**Comment by vpodk** [comment]
Hi @vilav, thank you for your questions. We have checked out and I want to confirm the following:
- there is no overlap between Komito and gtag.js;
- the implementation of Komito will not be affected;
- there is no difference for Komito to work with gtag.js or analytics.js.

Thank you,
Valentin

**Comment by vilbht** [comment]
thanks @vpodk !

quick follow-up: Any influence of the new iOS11 Intelligent Tracking Prevention (https://webkit.org/blog/7675/intelligent-tracking-prevention/) on Komito?

**Comment by vpodk** [comment]
Hi @vilav,

Thank you for your question.

Komito is an extension for other services and does not use cookies or sends direct HTTP requests.
Komito uses the API methods of services such as Google Analytics Events Tracking and 
Social Interactions:
- [`ga('send', 'event', ...)`](https://developers.google.com/analytics/devguides/collection/analyticsjs/events)
- [`ga('send', 'social', ...)`](https://developers.google.com/analytics/devguides/collection/analyticsjs/social-interactions)

Sincerely,
Valentin

**Comment by vpodk** [comment]
There is a great short video about gtag from @LovesData:
[gtag.js – Do you need Google's new Global Site Tag?](https://www.youtube.com/watch?v=IH_iExPV1no)

And there is a great explanation about it:
[New Global Site Tag Offers Unified Google Product Tracking](https://www.e-nor.com/blog/google-analytics/google-analytics-new-global-site-tag-offers-unified-google-product-tracking)
