### ISSUE TITLE
[gh-pages] Demo Console Errors

### ISSUE THREAD

**Issue by franz-josef-kaiser** [Datamart/Komito#28]
Reproduce issue: [Open Demo on GH–Pages site](https://komito.net/demo/).

YouTube responds with a `401`/ `unauthorized` Response to the `POST` request.

Maybe the account got disconnected, the auth layer in the YT API changed, the credentials are wrong or the file where the credentials originate from is gone?

**Comment by krailo** [comment]
Hi Franz,

Thanks for reaching out. Komito Analytics does not use any credentials for YouTube.  It looks like an error `401` could be related to the visitor who sees the video.  As a suggestion, the video could be blocked for certain visitors or regions.

We would like to help to investigate this issue.  Can you please provide more details on how to reproduce it?  Please send steps to reproduce to support@komito.net.  If you can attach screenshots they will help a lot, too.

Best regards,
Alex Krailo
Komito Team

**Comment by vpodk** [comment]
Hi @franz-josef-kaiser,

Is this issue still actual?

Thank you,
Valentin
