### ISSUE TITLE
komito analytics not working

### ISSUE THREAD

**Issue by bghaderian** [Datamart/Komito#29]

**Comment by vpodk** [comment]
Hi @bghaderian,

According to your video, it seems you missed insert the komito script. You have pasted only the configuration part.

Please add komito.js before or after the configurations (https://youtu.be/zrI0FlNSSA0?t=1m56s):
<img width="928" alt="screen shot 2018-03-05 at 9 05 37 am" src="https://user-images.githubusercontent.com/11623226/36988786-94072234-2054-11e8-910f-496d4b9e231b.png">

Please let us know if you have any questions.

Thank you,
Valentin

**Comment by bghaderian** [comment]
Hi Thank you for pointing that out. I made the changes but I still don't see any events being tracked.

updated video: https://drive.google.com/file/d/107oRVRLAgZVejD_XGJLCQqz6mChnLuv0/view

**Comment by vpodk** [comment]
I'm trying to debug and looks like all events and social interactions are sent successfully:

<img width="1386" alt="screen shot 2018-03-05 at 11 08 26 am" src="https://user-images.githubusercontent.com/11623226/36994523-3afb6364-2066-11e8-9ec5-25c3aaaff5c7.png">

<img width="1386" alt="screen shot 2018-03-05 at 11 11 54 am" src="https://user-images.githubusercontent.com/11623226/36994522-3adadcfc-2066-11e8-95b7-dd711b7948ee.png">

Can you please check if '**UA-104383497-1**' is correct Google Analytics property?
<img width="533" alt="screen shot 2018-03-05 at 11 25 00 am" src="https://user-images.githubusercontent.com/11623226/36995137-0b865d44-2068-11e8-9a5d-5720fc230ea2.png">

Thank you,
Valentin

**Comment by bghaderian** [comment]
Hi Valentin, I just remembered I have blocked my own IP hence why none of my events are showing. I just disabled my filter to test this and it worked. Thank you for your help, issue is fixed :)
