### ISSUE TITLE
Shopify Integration: Does not track add to cart, checkout, etc.

### ISSUE THREAD

**Issue by rhokstar** [Datamart/Komito#31]
I tried this on a Shopify website and its not tracking most the events (i.e. add to cart, checkout, etc.). However in a Wordpress site, its tracking form submits and other events. Has anyone integrated with Shopify?

I implemented the script as prescribed but in the theme.liquid file.

**Comment by vpodk** [comment]
Hi @rhokstar, thank you for reporting this issue.

Can you please provide us your website URL?
If you do not want to publish it here, you can send it to support(at)komito.net.

Thank you,
Valentin

**Comment by vpodk** [comment]
Hi @rhokstar ,

Is this issue still actual?

Thank you,
Valentin

**Comment by rhokstar** [comment]
Hi @vpodk,

I decided to remove Komito from Shopify. Shopify and Google Analytics are pickup up events just fine but there are other events I'd like to collect but are not important at the moment.

Thanks for following up,

Jonathan
