### ISSUE TITLE
Add support to uBlock

### ISSUE THREAD

**Issue by Tropicalista** [Datamart/Komito#34]
At the moment adblock trackers doesn't seem well implemented. I have tested with uBlock and I didn't got any hit on site with Adsense.

Also in the debug there is no output of adblock.

Reference: https://github.com/Datamart/Komito/pull/33

**Comment by vpodk** [comment]
I installed the latest version (0.9.5.8) of [uBlock](https://chrome.google.com/webstore/detail/ublock/epcnnfbjfcgphgdmggkamkmgojdagdnn/) for Chrome and it looks like Komito detect it:

<img width="928" alt="screen shot 2018-10-05 at 5 12 11 pm" src="https://user-images.githubusercontent.com/11623226/46565202-e457c200-c8c1-11e8-8558-60f05680fe6e.png">

@Tropicalista, can you please provide the URL of the website or page where you are trying to use this feature?

**Comment by Tropicalista** [comment]
I'm using it here: https://www.calcolo-mutuo.net/

You can check the console for debug.

**Comment by vpodk** [comment]
Got it. 

> To enable AdBlockers tracking, you need to enable this feature, because it is disabled by default:

```javascript
'trackAdblock': 0,    // Tracks page views with blocked ads. (Experimental)
```

Just add `trackAdblock: 1` to the Komito config:
<img width="959" alt="screen shot 2018-10-05 at 5 42 24 pm" src="https://user-images.githubusercontent.com/11623226/46565622-1408c900-c8c6-11e8-8f61-bbe8de80b63f.png">

**Comment by Tropicalista** [comment]
@vpodk You're correct about this.

However I got confused because I have made test on localhost where I was using the avinash script I posted and that script was conflicting with komito. 

After some checking I can confirm your script is correctly detecting uBlock, uBlock Origin and AdBlock.

Many thanks for your help.

**Comment by vpodk** [comment]
Awesome! Can I close this issue?

**Comment by Tropicalista** [comment]
Sure!!!

**Comment by vpodk** [comment]
@Tropicalista, BTW, for WordPress sites you can use our plugin:
- https://wordpress.org/plugins/komito-analytics/
- https://github.com/Datamart/Komito-WP
