### ISSUE TITLE
Is possible to customize the event action name?

### ISSUE THREAD

**Issue by Tropicalista** [Datamart/Komito#36]
As the title says,

I'd like to customize the event category and action name?

**Comment by vpodk** [comment]
In the current implementation, this is not possible.

I will add an `onBeforeTrack` event, where you can change the category and action names and even prevent sending specific metrics.

**Comment by vpodk** [comment]
@Tropicalista, try the following code:

```js
var _komito = _komito || {
  ...
 
  onBeforeTrack: function(event) {
    // Change event.type, event.category, event.action or event.label here.
    if (event.category == 'scroll' && event.action == 'depth') {
      event.action = 'Scroll Depth';
    }

    // Prevent sending the data to the trackers for the specific metric:
    if (event.category == 'video:vimeo') {
      event.preventDefault();
    }
  }
};
```

**Comment by Tropicalista** [comment]
I've tested and seems to work well. Thanks

**Comment by Tropicalista** [comment]
Hi, sorry if I ask here, but is a related clarification.

Is it possible to set a custom dimension on this, somenthing like:

```
var _komito = _komito || {
  ...
 
  onBeforeTrack: function(event) {
    // Prevent sending the data to the trackers for the specific metric:
    if (event.category == 'adblock') {
      ga('set', 'dimension1', true);
    }
  }
};
```

or this will be not executed?

**Comment by vpodk** [comment]
Hi @Tropicalista, yes, absolutely.  

It will be executed for all events tracked by Komito Analytics and you can put any code inside the event handler.

Thank you for the great use case!
