### ISSUE TITLE
Google Analytics Bounce Rates

### ISSUE THREAD

**Issue by bluecherryau** [Datamart/Komito#38]
I am using Komito in GTM for all of my clients, and I have an issue with bounce rate report since 1 Jan 2020. Bounce rates have dropped off dramatically. Is this a known issue with Komito?
Thanks for any help.

**Comment by vpodk** [comment]
Thank you for using Komito Analytics.
It sounds like you have an empty or missing `nonInteraction` parameter, only this parameter may affect the bounce rate.
Check it out, and if that doesn't help, please send more information to support@komito.net

**Comment by vpodk** [comment]
On December 31, we added [color scheme](https://komito.net/posts/track-color-scheme/) tracking.
And looks like you need to add `'color-scheme'` to the `nonInteraction` parameter:

```
'nonInteraction': ['adblock', 'audio', 'color-scheme', 'form', 'heartbeat', 'orientation', 'print', 'scroll', 'video']
```

Or you can disable this feature by setting `trackColorScheme` to `0`.

**Comment by vpodk** [comment]
Forced [`markAsNonInteractionEvent('color-scheme')`](https://github.com/Datamart/Komito/blob/master/src/komito/trackers/dom/__ns__.js#L82) as part of this commit: bad023c559370666c78423cd8dbc32a93b54acf9

@bluecherryau, thank you for reporting this issue.
