### ISSUE TITLE
Self hosting and/or Subresource integrity

### ISSUE THREAD

**Issue by synth** [Datamart/Komito#42]
Can the Komito javascript be self hosted or can subresource integrity be implemented with the hosted file?

As we all know, loading javascript from a third party domain is risky. Subresource integrity is one way to handle this, but also self-hosting can be an option. I'm guessing we can possibly save the minified komito.js to our own server, but I couldn't tell if that file was just a loader and would end up loading a separate file from a remote resource. 

Seems like it can be self hosted, but wanted to see what the community had to say on the matter. 

Thanks!

**Comment by vpodk** [comment]
@synth, yes of course you can just download the minified [komito.js](https://komito.net/komito.js) file and serve it from your web server.  You are not the first person to ask us this question.  Usually this question arises about how to change the caching policy and the best option is to serve it from your own web server.

**Comment by synth** [comment]
Thanks for your response @vpodk. So, then to confirm, the komito.js file does not download any additional assets? I see there is XMLHttpRequest handling in that file, but I don't know how it's used.

**Comment by vpodk** [comment]
Sorry, I forgot to mention that. Yes, the script is self-contained and does not load any additional assets.

`XMLHttpRequest` is used when you want to track the error pages ([integration page](https://komito.net/integration/)):
- `trackErrorPages` - Tracks error page using HTTP status code. This is an experimental feature.

If it is enabled, it will send an HTTP HEAD request to the current page URL and check the response status code:
https://github.com/Datamart/Komito/blob/master/src/komito/trackers/dom/__ns__.js#L47

**Comment by synth** [comment]
Awesome, thanks!
